[tool.poetry]
name = "gfpgan-webui"
version = "0.1.0"
description = ""
authors = ["Huy Nguyen <giahuy2201@icloud.com>"]
readme = "README.md"

[[tool.poetry.source]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm5.7"
priority = "explicit"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
gfpgan = "^1.3.8"
gradio = "^4.29.0"
realesrgan = "^0.3.0"
opencv-python = "^4.9.0.80"
pytorch-triton-rocm = {version = "^2.1.2", source = "pytorch-rocm"}
torch = {version = "^2.1.2", source = "pytorch-rocm"}
torchvision = {version = "^0.17.0+rocm5.7", source = "pytorch-rocm"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
